permalink: /blog/:title/
highlighter: pygments
markdown: kramdown
excerpt_separator: <!--more-->
kramdown:
    auto_ids: false
    parse_block_html: true

defaults:
    -
        scope:
            path: ""      # empty string for all files
            type: posts   # limit to posts
        values:
            is_post: true # automatically set is_post=true for all posts
